USE biblioteca_digital;

INSERT INTO recursos_digitales (titulo, tipo, tipo_suscripcion) VALUES
('Introducción a la Programación', 'Libro', 'gratuita'),
('Historia del Arte Moderno', 'Libro', 'premium'),
('Guía de Fotografía Digital', 'Tutorial', 'gratuita'),
('Inteligencia Artificial para Principiantes', 'Libro', 'premium'),
('Fundamentos de Matemáticas', 'Libro', 'gratuita'),
('Diseño Gráfico Avanzado', 'Tutorial', 'premium'),
('Psicología del Aprendizaje', 'Artículo', 'gratuita'),
('Programación en Python: Nivel Intermedio', 'Libro', 'premium'),
('Cómo Crear Podcasts', 'Tutorial', 'gratuita'),
('Bases de Datos Relacionales', 'Libro', 'premium'),
('Desarrollo de Videojuegos', 'Tutorial', 'gratuita'),
('Historia de la Música Clásica', 'Audiolibro', 'premium'),
('Estrategias de Marketing Digital', 'Artículo', 'gratuita'),
('Aprende SQL Paso a Paso', 'Libro', 'premium'),
('Introducción al Big Data', 'Libro', 'gratuita'),
('Diseño Web con HTML y CSS', 'Tutorial', 'premium'),
('Redacción Creativa', 'Libro', 'gratuita'),
('Aprendizaje Automático Avanzado', 'Libro', 'premium'),
('Psicología Cognitiva', 'Artículo', 'gratuita'),
('Guía Completa de Photoshop', 'Tutorial', 'premium'),
('Historia del Cine Contemporáneo', 'Audiolibro', 'gratuita'),
('Fundamentos de Física', 'Libro', 'premium'),
('Cómo Programar en Java', 'Libro', 'gratuita'),
('Técnicas de Ilustración Digital', 'Tutorial', 'premium'),
('Investigación en Ciencias Sociales', 'Investigación', 'gratuita'),
('Aprende JavaScript en 30 Días', 'Libro', 'premium'),
('Marketing de Contenidos', 'Artículo', 'gratuita'),
('Programación Orientada a Objetos', 'Libro', 'premium'),
('Diseño de Interfaces UX/UI', 'Tutorial', 'gratuita'),
('Historia de la Literatura', 'Libro', 'premium'),
('Algoritmos y Estructuras de Datos', 'Libro', 'gratuita'),
('Fotografía Nocturna', 'Tutorial', 'premium'),
('Neuromarketing y Comportamiento del Consumidor', 'Artículo', 'gratuita'),
('Aprende Ciberseguridad', 'Libro', 'premium'),
('Diseño de Juegos Mobile', 'Tutorial', 'gratuita'),
('Introducción a la Filosofía', 'Libro', 'premium'),
('Psicología del Color', 'Artículo', 'gratuita'),
('Cómo Crear Videos Educativos', 'Tutorial', 'premium'),
('Historia de la Ciencia', 'Libro', 'gratuita'),
('Machine Learning Práctico', 'Libro', 'premium'),
('Audiolibro: Grandes Inventos', 'Audiolibro', 'gratuita'),
('Estrategias de Negocios', 'Artículo', 'premium'),
('Programación Funcional en Python', 'Libro', 'gratuita'),
('Tutorial de Illustrator', 'Tutorial', 'premium'),
('Investigación sobre Cambio Climático', 'Investigación', 'gratuita'),
('Aprendizaje Profundo', 'Libro', 'premium'),
('Historia de la Arquitectura', 'Libro', 'gratuita'),
('Diseño de Experiencias de Usuario', 'Tutorial', 'premium'),
('Psicología del Desarrollo Infantil', 'Artículo', 'gratuita'),
('Fundamentos de Química', 'Libro', 'premium'),
('Cómo Crear Aplicaciones Móviles', 'Tutorial', 'gratuita'),
('Audiolibro: Filosofía Contemporánea', 'Audiolibro', 'premium'),
('Big Data y Análisis de Datos', 'Libro', 'gratuita'),
('Historia de la Literatura Española', 'Libro', 'premium'),
('Tutorial de After Effects', 'Tutorial', 'gratuita'),
('Marketing en Redes Sociales', 'Artículo', 'premium'),
('Programación Avanzada en C++', 'Libro', 'gratuita'),
('Diseño y Producción Musical', 'Tutorial', 'premium'),
('Investigación en Biología', 'Investigación', 'gratuita'),
('Aprende R para Estadística', 'Libro', 'premium'),
('Historia del Teatro', 'Libro', 'gratuita'),
('Tutorial de Premiere Pro', 'Tutorial', 'premium'),
('Psicología Social', 'Artículo', 'gratuita'),
('Fundamentos de Economía', 'Libro', 'premium'),
('Cómo Crear Comics Digitales', 'Tutorial', 'gratuita'),
('Audiolibro: Historia del Universo', 'Audiolibro', 'premium'),
('Diseño de Aplicaciones Web', 'Tutorial', 'gratuita'),
('Aprendizaje Automático con TensorFlow', 'Libro', 'premium'),
('Historia de la Fotografía', 'Libro', 'gratuita'),
('Marketing para Startups', 'Artículo', 'premium'),
('Programación en Ruby', 'Libro', 'gratuita'),
('Tutorial de 3D con Blender', 'Tutorial', 'premium'),
('Investigación en Psicología', 'Investigación', 'gratuita'),
('Aprende Node.js', 'Libro', 'premium'),
('Historia de la Música Jazz', 'Libro', 'gratuita'),
('Diseño de Prototipos UX', 'Tutorial', 'premium'),
('Psicología de la Motivación', 'Artículo', 'gratuita'),
('Fundamentos de Sociología', 'Libro', 'premium'),
('Cómo Crear Contenido para YouTube', 'Tutorial', 'gratuita'),
('Audiolibro: Grandes Descubrimientos', 'Audiolibro', 'premium'),
('Big Data Aplicado', 'Libro', 'gratuita'),
('Historia del Diseño Industrial', 'Libro', 'premium'),
('Tutorial de Animación 2D', 'Tutorial', 'gratuita'),
('Marketing de Influencers', 'Artículo', 'premium'),
('Programación Web con PHP', 'Libro', 'gratuita'),
('Diseño de Videojuegos 3D', 'Tutorial', 'premium'),
('Investigación en Historia', 'Investigación', 'gratuita'),
('Aprende SQL Avanzado', 'Libro', 'premium'),
('Historia de la Filosofía', 'Libro', 'gratuita'),
('Tutorial de Maya', 'Tutorial', 'premium'),
('Psicología del Trabajo', 'Artículo', 'gratuita'),
('Fundamentos de Geografía', 'Libro', 'premium'),
('Cómo Crear Apps de Realidad Aumentada', 'Tutorial', 'gratuita'),
('Audiolibro: Ciencias de la Tierra', 'Audiolibro', 'premium'),
('Diseño de Interfaces Móviles', 'Tutorial', 'gratuita'),
('Aprendizaje Automático con Python', 'Libro', 'premium'),
('Historia del Cine Latinoamericano', 'Libro', 'gratuita'),
('Marketing Digital Avanzado', 'Artículo', 'premium'),
('Programación en Kotlin', 'Libro', 'gratuita'),
('Tutorial de Photoshop Avanzado', 'Tutorial', 'premium'),
('Investigación en Tecnología Educativa', 'Investigación', 'gratuita'),
('Aprende Java Avanzado', 'Libro', 'premium'),
('Historia de la Música Pop', 'Libro', 'gratuita'),
('Diseño de Juegos Indie', 'Tutorial', 'premium'),
('Psicología del Aprendizaje Digital', 'Artículo', 'gratuita'),
('Fundamentos de Estadística', 'Libro', 'premium'),
('Cómo Crear Cursos Online', 'Tutorial', 'gratuita'),
('Audiolibro: Grandes Matemáticos', 'Audiolibro', 'premium'),
('Big Data para Empresas', 'Libro', 'gratuita'),
('Historia del Arte Barroco', 'Libro', 'premium'),
('Tutorial de Illustrator Avanzado', 'Tutorial', 'gratuita'),
('Marketing de Contenidos Creativos', 'Artículo', 'premium'),
('Programación Funcional en JavaScript', 'Libro', 'gratuita'),
('Diseño de Experiencias Interactivas', 'Tutorial', 'premium'),
('Investigación en Ciencias de la Computación', 'Investigación', 'gratuita'),
('Aprende Python para Data Science', 'Libro', 'premium');
('Introducción a la Robótica', 'Libro', 'premium'),
('Historia del Pensamiento Económico', 'Libro', 'gratuita'),
('Diseño Editorial Digital', 'Tutorial', 'premium'),
('Programación con Go', 'Libro', 'gratuita'),
('Análisis de Datos con Excel', 'Tutorial', 'premium'),
('Psicología de la Comunicación', 'Artículo', 'gratuita'),
('Cómo Escribir Ensayos Académicos', 'Tutorial', 'premium'),
('Fundamentos de Arquitectura Moderna', 'Libro', 'gratuita'),
('Investigación en Astronomía', 'Investigación', 'premium'),
('Audiolibro: Historia del Arte Renacentista', 'Audiolibro', 'gratuita'),
('Aprende HTML5 y CSS3', 'Tutorial', 'premium'),
('Introducción a la Criptografía', 'Libro', 'gratuita'),
('Diseño de Bases de Datos', 'Tutorial', 'premium'),
('Marketing para Emprendedores', 'Artículo', 'gratuita'),
('Investigación en Energías Renovables', 'Investigación', 'premium'),
('Guía Completa de Lightroom', 'Tutorial', 'gratuita'),
('Historia de la Filosofía Griega', 'Libro', 'premium'),
('Fundamentos del Derecho Internacional', 'Libro', 'gratuita'),
('Psicología del Liderazgo', 'Artículo', 'premium'),
('Audiolibro: Grandes Civilizaciones', 'Audiolibro', 'gratuita'),
('Diseño de Experimentos Científicos', 'Libro', 'premium'),
('Cómo Crear Presentaciones Efectivas', 'Tutorial', 'gratuita'),
('Introducción a la Programación en C#', 'Libro', 'premium'),
('Investigación en Inteligencia Artificial', 'Investigación', 'gratuita'),
('Aprende Edición de Video', 'Tutorial', 'premium'),
('Historia de la Comunicación Social', 'Libro', 'gratuita'),
('Fundamentos de Ingeniería de Software', 'Libro', 'premium'),
('Diseño de Bases de Datos NoSQL', 'Tutorial', 'gratuita'),
('Psicología del Aprendizaje Infantil', 'Artículo', 'premium'),
('Audiolibro: Historia del Pensamiento Científico', 'Audiolibro', 'gratuita'),
('Programación para Data Science', 'Libro', 'premium'),
('Investigación en Biotecnología', 'Investigación', 'gratuita'),
('Diseño de Portales Web', 'Tutorial', 'premium'),
('Historia del Arte Asiático', 'Libro', 'gratuita'),
('Aprende a Usar Power BI', 'Tutorial', 'premium'),
('Guía de Comunicación Escrita', 'Artículo', 'gratuita'),
('Fundamentos de Contabilidad', 'Libro', 'premium'),
('Audiolibro: Grandes Descubrimientos Médicos', 'Audiolibro', 'gratuita'),
('Investigación en Neurociencia', 'Investigación', 'premium'),
('Programación en Swift', 'Libro', 'gratuita'),
('Cómo Crear un Podcast Educativo', 'Tutorial', 'premium'),
('Historia del Pensamiento Político', 'Libro', 'gratuita'),
('Psicología del Trabajo en Equipo', 'Artículo', 'premium'),
('Diseño de Experiencias Educativas', 'Tutorial', 'gratuita'),
('Fundamentos de Astronomía', 'Libro', 'premium'),
('Investigación en Física Cuántica', 'Investigación', 'gratuita'),
('Aprende a Diseñar Infografías', 'Tutorial', 'premium'),
('Historia del Cine Europeo', 'Libro', 'gratuita'),
('Fundamentos de Biología Molecular', 'Libro', 'premium'),
('Psicología de la Creatividad', 'Artículo', 'gratuita'),
('Audiolibro: Grandes Pintores del Siglo XX', 'Audiolibro', 'premium'),
('Diseño de Experiencias de Aprendizaje', 'Tutorial', 'gratuita'),
('Programación Web Avanzada', 'Libro', 'premium'),
('Investigación en Educación Digital', 'Investigación', 'gratuita'),
('Historia del Diseño de Moda', 'Libro', 'premium'),
('Cómo Crear Mapas Conceptuales', 'Tutorial', 'gratuita'),
('Fundamentos de la Ética', 'Libro', 'premium'),
('Psicología del Consumidor', 'Artículo', 'gratuita'),
('Audiolibro: Descubrimientos Astronómicos', 'Audiolibro', 'premium'),
('Diseño de Experiencias Multimediales', 'Tutorial', 'gratuita'),
('Aprende PowerPoint Avanzado', 'Tutorial', 'premium'),
('Historia del Arte Latinoamericano', 'Libro', 'gratuita'),
('Fundamentos de Electrónica', 'Libro', 'premium'),
('Investigación en Genética Humana', 'Investigación', 'gratuita'),
('Psicología del Lenguaje', 'Artículo', 'premium'),
('Diseño de Ilustraciones Digitales', 'Tutorial', 'gratuita'),
('Programación en Rust', 'Libro', 'premium'),
('Audiolibro: Grandes Aventuras Científicas', 'Audiolibro', 'gratuita'),
('Historia de la Revolución Industrial', 'Libro', 'premium'),
('Cómo Crear Blogs Educativos', 'Tutorial', 'gratuita'),
('Fundamentos de Finanzas', 'Libro', 'premium'),
('Psicología de la Personalidad', 'Artículo', 'gratuita'),
('Investigación en Historia del Arte', 'Investigación', 'premium'),
('Aprende Adobe XD', 'Tutorial', 'gratuita'),
('Historia de la Literatura Infantil', 'Libro', 'premium'),
('Diseño de Diagramas de Flujo', 'Tutorial', 'gratuita'),
('Fundamentos de Programación', 'Libro', 'premium'),
('Audiolibro: Grandes Pensadores del Siglo XIX', 'Audiolibro', 'gratuita'),
('Psicología del Aprendizaje Online', 'Artículo', 'premium'),
('Investigación en Robótica Educativa', 'Investigación', 'gratuita'),
('Diseño de Páginas Responsivas', 'Tutorial', 'premium'),
('Historia del Arte Contemporáneo', 'Libro', 'gratuita'),
('Fundamentos de Economía Internacional', 'Libro', 'premium'),
('Cómo Crear Diagramas UML', 'Tutorial', 'gratuita'),
('Audiolibro: Descubrimientos Tecnológicos', 'Audiolibro', 'premium'),
('Psicología del Comportamiento Social', 'Artículo', 'gratuita'),
('Investigación en Ecología Marina', 'Investigación', 'premium'),
('Programación en PHP Moderno', 'Libro', 'gratuita'),
('Diseño de Proyectos Educativos', 'Tutorial', 'premium'),
('Historia del Arte Precolombino', 'Libro', 'gratuita'),
('Fundamentos de Medicina General', 'Libro', 'premium'),
('Psicología Positiva', 'Artículo', 'gratuita'),
('Audiolibro: Historia de la Ciencia Moderna', 'Audiolibro', 'premium'),
('Diseño de Recursos Digitales Educativos', 'Tutorial', 'gratuita'),
('Investigación en Ingeniería Civil', 'Investigación', 'premium'),
('Historia de la Literatura Francesa', 'Libro', 'gratuita'),
('Aprende Desarrollo Frontend', 'Tutorial', 'premium'),
('Fundamentos de Microeconomía', 'Libro', 'gratuita'),
('Psicología de la Memoria', 'Artículo', 'premium'),
('Audiolibro: Grandes Descubrimientos Físicos', 'Audiolibro', 'gratuita'),
('Diseño de Cursos Virtuales', 'Tutorial', 'premium'),
('Programación en Perl', 'Libro', 'gratuita'),
('Investigación en Educación Inclusiva', 'Investigación', 'premium'),
('Historia del Arte Islámico', 'Libro', 'gratuita'),
('Fundamentos de Macroeconomía', 'Libro', 'premium'),
('Psicología del Estrés', 'Artículo', 'gratuita'),
('Audiolibro: Historia de las Ideas Políticas', 'Audiolibro', 'premium'),
('Diseño de Contenidos Interactivos', 'Tutorial', 'gratuita'),
('Investigación en Inteligencia Ambiental', 'Investigación', 'premium'),
('Aprende Docker desde Cero', 'Tutorial', 'gratuita'),
('Historia del Diseño Tipográfico', 'Libro', 'premium'),
('Fundamentos de Ingeniería Ambiental', 'Libro', 'gratuita'),
('Psicología de la Educación', 'Artículo', 'premium'),
('Audiolibro: Grandes Viajes de Exploración', 'Audiolibro', 'gratuita'),
('Diseño de Infografías Educativas', 'Tutorial', 'premium'),
('Investigación en Ciencias Políticas', 'Investigación', 'gratuita'),
('Programación con Kotlin', 'Libro', 'premium'),
('Historia del Arte Bizantino', 'Libro', 'gratuita');